### ISSUE TITLE
make sure that all the localization strings are correctly used on the website - REACT side

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#146]
## Current situation

all the messages that Sefaria had split in many strings are now single strings with placeholders

## Todo

- [x] check that all the tibetan strings in Figma are single strings in Tolgee with placeholders
- [x] check that all the new translations from Figma are applied on the website and that they are in Tolgee
- [x] add tag "figma" to all strings that are in Figma
- [x] Ensure that all the strings that needed to be updated/added/removed as described in Figma have been processed correctly

Note: please make sure that the strings behind placeholders are also in Tolgee (like ཟླ། བདུན། ཉིན། and the numbers ༡ ༢ ༣ etc.)

**Comment by drupchen** [comment]
waiting for the DJANGO side to test together in Tolgee
