### ISSUE TITLE
compare FigJam, Tolgee and production and check that everything is as expected (REACT JS )

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#180]
# Situation

After having moved localization to Tolgee, we need to make sure everything in production is as it was expected in the FigJam

# Todo:
- open at the same time: Figma on the left, pecha website in the middle, Tolgee at the right
- Check that what is on the website is the same as Figma
    - check that all the strings are there
    - check that there are no old strings on the website
    - check that all the split strings in Sefaria are now correctly joined with patterns/variables
- Check that Tolgee has the same strings as Figma and the website

# Steps

- [x] Open side by side FigJam, Tolgee and the website
- [x] check that the website corresponds to what is in FigJam
- [x] If it doesn't correspond, update Tolgee strings

# Still not applied
- [x] sapche
![Image](https://github.com/user-attachments/assets/71ef3439-a5d2-4577-870c-cb6263c66b1f)

should be: "Section" instead of sapche

- [x] category not in bo even if locale is set in Tibetan
![Image](https://github.com/user-attachments/assets/1049b2b9-9f1e-4a43-9392-7833ecdd261d)

- [x] ཧེ་བྲུ། and Hebrew
![Image](https://github.com/user-attachments/assets/5b3d38f0-7ceb-4e38-884e-0be821d0a368)
![Image](https://github.com/user-attachments/assets/b09c6a85-cf3c-44b7-a1c8-93c46fe5429d)

Should be བོད་སྐད།

- [x] again
![Image](https://github.com/user-attachments/assets/45096152-1113-4355-a745-057c3923ab6f)
![Image](https://github.com/user-attachments/assets/68ecaa34-e0ee-4d28-89d3-65fa20857176)

- [x] why is it different in different texts?
![Image](https://github.com/user-attachments/assets/af4a810e-9f0d-4263-a9fe-e42697cd7cc8)
![Image](https://github.com/user-attachments/assets/0dabc2b4-bab1-483f-8d3f-df07c22b6f1c)

- [x] tibetan misnamed
![Image](https://github.com/user-attachments/assets/28065b59-7b39-41ec-851c-bab912fc345e)

- [x] are all these language name strings in Tolgee?
![Image](https://github.com/user-attachments/assets/eb9c090c-5501-4a06-82a8-a44344be241f)

- [x] are these strings in Tolgee?
![Image](https://github.com/user-attachments/assets/25f365e1-125d-4a19-8b1d-8268c4cf5930)
![Image](https://github.com/user-attachments/assets/fc5c8ff8-871a-407e-bd47-6aa237071cfd)
![Image](https://github.com/user-attachments/assets/71d86865-20a1-4fc2-baeb-4d34bd3f5033)
![Image](https://github.com/user-attachments/assets/5a499af0-5952-4d88-b5a7-80d6296e6095)

- [x]  not applied
![Image](https://github.com/user-attachments/assets/103ba87d-ff82-4214-b3e7-ad9500b9c868)
![Image](https://github.com/user-attachments/assets/2f636335-8071-4fbb-a6dd-a8f2b29b696f)

- [x] not applied
![Image](https://github.com/user-attachments/assets/8e1852a1-ee26-44da-9af0-a0a3ba2d8c15)
![Image](https://github.com/user-attachments/assets/07d285fc-180b-4099-b03a-0c8440f74dd4)

- [x] missing strings in Figma (to add in Tolgee)
![Image](https://github.com/user-attachments/assets/3c9fe31e-1056-4719-9cb4-ff0bd31ba9b6)
![Image](https://github.com/user-attachments/assets/dc9e2289-f4d4-4f75-bbba-ea4ecc0624c2)
Should be མ་ཡིག།

- [x]  Tibetan not applied
![Image](https://github.com/user-attachments/assets/851e5184-56fe-42fc-89a7-52b5f2a7df7c)
![Image](https://github.com/user-attachments/assets/37b66453-b2b5-42be-8cad-b71c156ac580)
Note: Hebrew should be Tibetan

- [x] not deleted BO string
![Image](https://github.com/user-attachments/assets/0c17ffaf-ab7d-46cd-bab7-820e70b63e74)
![Image](https://github.com/user-attachments/assets/0fe34759-af63-40d6-abaf-290f80b3c94a)

- [x] can't check button text because text hidden
![Image](https://github.com/user-attachments/assets/ea762dfd-e6b1-4e5f-a4b9-a06c184cf43b)
![Image](https://github.com/user-attachments/assets/373bcd3d-8ff2-49f1-874a-8ea7e4ace83c)

- [x] wrong message
![Image](https://github.com/user-attachments/assets/79da2cbf-a90c-4031-9614-14ddeca5c501)
![Image](https://github.com/user-attachments/assets/98d53a44-06dd-40ed-aa65-a91f7a0d3857)

- [x] not applied
![Image](https://github.com/user-attachments/assets/9e196fb7-27fe-4daf-ba0f-4f3dc1515da0)
![Image](https://github.com/user-attachments/assets/8f63f237-270f-4a77-a6f5-07dffcaa24f8)

- [x] not applied
![Image](https://github.com/user-attachments/assets/c3258acf-a0e2-4099-956c-fb34f3c88873)
![Image](https://github.com/user-attachments/assets/ac4bae50-e875-458e-9de1-17fd44adfe91)

- [x] missing in Figma to add in Tolgee and modify
![Image](https://github.com/user-attachments/assets/b21cea8d-58b3-41fc-9aa5-ca216132adce)
![Image](https://github.com/user-attachments/assets/d179bc9e-c617-46b1-b6ac-24a46c1b6d9e)

should be: `{xxx} ནང་ལ་འདིའི་འགྲེལ་བ་མི་འདུག།`

- [x] bo string not added
![Image](https://github.com/user-attachments/assets/d6841568-1da5-4f63-87a1-bb3a4a75d8f3)
![Image](https://github.com/user-attachments/assets/658fc487-4130-4c9c-9572-1cba08cb4fa0)

- [x] not applied
![Image](https://github.com/user-attachments/assets/43276e25-ce1f-45c7-8f29-8bd11195bbb7)
![Image](https://github.com/user-attachments/assets/5a44ce30-7a31-4b9c-b68d-3bdea275742d)

- [x] not  applied
![Image](https://github.com/user-attachments/assets/b1f38449-8bb1-4101-b8c8-2086275f0d8a)
![Image](https://github.com/user-attachments/assets/7cbde34e-d42f-4bad-893f-2ed54c3087b6)

- [x] not translated
![Image](https://github.com/user-attachments/assets/d9264853-064b-46e3-9522-dbf21a55bf74)
![Image](https://github.com/user-attachments/assets/99852382-3d98-4e57-bec6-13fbd37b6dee)

- [x] not applied
![Image](https://github.com/user-attachments/assets/d92b871b-606c-4b19-a009-33ca87280d49)
![Image](https://github.com/user-attachments/assets/baaa6e6f-826f-418b-a214-af1f7b8e6ee8)

- [x] not applied
![Image](https://github.com/user-attachments/assets/8452dfff-0652-40f8-995d-5dc2a2338a24)
![Image](https://github.com/user-attachments/assets/9b952a89-9b52-4408-8b02-53a50f1067e6)

- [x] not applied
![Image](https://github.com/user-attachments/assets/99f17270-3b03-4ea6-b718-0b48c34b72c2)
![Image](https://github.com/user-attachments/assets/9719eb89-7edb-4ae3-8096-72a0170395a5)

- [x] not applied
![Image](https://github.com/user-attachments/assets/e05420ca-1779-4a39-89b1-8b286387a42d)
![Image](https://github.com/user-attachments/assets/a60666ab-6e29-4df8-aad9-5fa8e4a79485)

- [x] not applied
![Image](https://github.com/user-attachments/assets/a1c4a94c-a258-4ff1-9604-592d43897457)
![Image](https://github.com/user-attachments/assets/f51bcda8-874f-4686-a558-9292c43c2edf)

- [x] not applied
![Image](https://github.com/user-attachments/assets/039ced7e-537e-429f-8b47-b90498f8562a)
![Image](https://github.com/user-attachments/assets/db8b5be6-a722-48db-ba62-eed35c40dce0)

- [x] still in English
![Image](https://github.com/user-attachments/assets/3c0b615c-6134-4071-b4f6-3bbb5f31c7b0)

- [x] not applied
![Image](https://github.com/user-attachments/assets/80e212bb-07d4-48e3-9024-9c58ffb0fa65)
![Image](https://github.com/user-attachments/assets/5877c394-06c7-4ae3-b115-fb7aea6fe84a)

- [x] not applied in Collections
![Image](https://github.com/user-attachments/assets/97217b7f-03a6-42fe-b1d1-3ccbc36edcc0)
![Image](https://github.com/user-attachments/assets/86303052-c9bb-43d0-8e2f-d0e4c0c18079)

- [x] no
![Image](https://github.com/user-attachments/assets/90114fbc-40b5-4474-9a8c-881d113cd0a1)
![Image](https://github.com/user-attachments/assets/55d4400c-fdd7-4ac7-8087-bab472a826ed)

- [x] doesn't follow pattern
![Image](https://github.com/user-attachments/assets/0660c301-09f4-4e85-b790-87346c21bee2)
![Image](https://github.com/user-attachments/assets/463adbb0-124d-4239-b8a3-119513b88ab2)

- [x] not applied
![Image](https://github.com/user-attachments/assets/53e53097-a053-4fdf-8bde-07c652233a70)
![Image](https://github.com/user-attachments/assets/26f97804-fbda-4388-901e-a85e291cfcc3)

- [x] bug and not applied
![Image](https://github.com/user-attachments/assets/158d2109-199a-45f1-904b-e13f34ab86f2)
![Image](https://github.com/user-attachments/assets/cafd43f4-6c0b-4f88-9465-19f798232e84)

- [x] not applied
![Image](https://github.com/user-attachments/assets/9a348b32-0404-4b47-a8b9-1537224e4af8)
![Image](https://github.com/user-attachments/assets/6913fa3a-2ae9-4b47-bd01-1b3eca53b640)

- [x] not applied
![Image](https://github.com/user-attachments/assets/e730c3fe-f6d2-42b4-a13c-2888155ad7bf)
![Image](https://github.com/user-attachments/assets/fa07f836-ad16-4ea3-a8d4-84b327930e13)

- [x] not applied
![Image](https://github.com/user-attachments/assets/55a4f2f6-4464-4f44-81ba-72d503423e58)
![Image](https://github.com/user-attachments/assets/4a65a8d7-4cb8-4a36-b6d1-916866c7e77c)

- [x] wrong string
![Image](https://github.com/user-attachments/assets/dc1d59de-67aa-49e6-8710-574214f6dafc)
![Image](https://github.com/user-attachments/assets/1321895f-ca49-42f6-85c7-9214cabf4525)

- [x] not translated
![Image](https://github.com/user-attachments/assets/b8406cdb-543d-4b4d-a2ad-d485e8a26f4b)

- [x] you have erased the `d` so `Save` doesn't have any tibetan string
![Image](https://github.com/user-attachments/assets/bca44e4e-f998-4df6-8daf-c1d836ceff68)

- [x] missing string in Figma
![Image](https://github.com/user-attachments/assets/586155f3-3735-498a-bc25-1b656855c2a8)
 should be `༑{xxx}༑ ལ་ཡོད་པའི་མཚམས་རྟགས་སུབ།`

- [x] not applied
![Image](https://github.com/user-attachments/assets/70b6a3b6-eb62-4872-ba7b-f0488430b0af)
![Image](https://github.com/user-attachments/assets/12ca2eed-2972-4498-accb-2bce19bcf256)

- [x] time stamp not applied
![Image](https://github.com/user-attachments/assets/3783778a-6c40-4d38-a30c-c669b69e379d)
![Image](https://github.com/user-attachments/assets/841fb49a-e68c-4aa0-b131-204d7be9c1db)

- [x] not applied
![Image](https://github.com/user-attachments/assets/a070e5f5-f29d-46d1-ae4a-cd7b50e56dfd)
![Image](https://github.com/user-attachments/assets/cb415212-2270-40e3-8144-0535ce6e7065)

- [x] not applied 
![Image](https://github.com/user-attachments/assets/80096ac6-a512-4152-8ee2-4436e5d2b18f)
![Image](https://github.com/user-attachments/assets/0570298e-11e0-4403-93a5-42799d71dd16)

- [x] not updated 
![Image](https://github.com/user-attachments/assets/311b3edc-1d17-409e-aca8-cf5c78e1d1de)
![Image](https://github.com/user-attachments/assets/0b999631-94ed-4817-9831-7c39e276a93b)

- [x] couldn't check Sources.
![Image](https://github.com/user-attachments/assets/647970bc-5292-4c4e-814d-4aade19a3353)
Don't know how to add sources to a topic
 
- [x] missing strings
![Image](https://github.com/user-attachments/assets/5b0c1277-7718-49b3-88aa-bfc2af4c56ae)
 should be:
- `Looks like we haven’t seen you in a while!` - `དེར་མ་ཕེབས་ཡུན་རིང་།`
- `Discover what other people are doing on Pecha...` - `བེད་སྤྱོད་མཁན་གཞན་གྱིས་བསྐྲུན་པར་གཟིགས།`
- `What People are Reading` - `གཞན་གྱིས་ཀློག་བཞིན་པར་གཟིགས།`
- `Top Categories` - `གཞན་གྱིས་བཀླགས་པ་མང་ཤོས།`

- [x] mixed strings
![Image](https://github.com/user-attachments/assets/ddee2603-a4d0-4fb1-9134-fc5c942b29a6)
![Image](https://github.com/user-attachments/assets/91593d11-2766-4b0e-9aa5-fc3d7b992c88)

- [x] Hebrew remaining
![Image](https://github.com/user-attachments/assets/e9530ee7-4c3a-480f-b0f1-86eeb589df67)
should be: ཁྱེད་རང་དགའ་ཤོས་ཀྱི་ཟིན་བྲིས།

- [x] string to be removed from UI
![Image](https://github.com/user-attachments/assets/8e57fe32-e7f7-4257-9715-8733f9821a33)
