### ISSUE TITLE
Solve sefaria's usage of message id and message string in po file

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#209]
## Description : 
In po file, the msgid field serves as the unique identifier for a translatable message.
But sefaria's has used the english strings itself as msgid. 
Example: 
```
#: templates/registration/register.html:13
msgid "Sign Up"
msgstr ""
```
While it works fine usually for translation in django, to integrate seamlessly with tolgee (for localization), this pose a big hurdles. 

Because in tolgee, a string need a unique id(with context)
![Image](https://github.com/user-attachments/assets/4f2d13be-c839-4528-979e-c2107f692218)

## Solution : 
All the strings in msgid field need to be replaced by unique identifier
Example : 
```
#: templates/registration/register.html:13
msgid "common.registration.register.sign_up"
msgstr "Sign Up"
```
# Expected result :
1. Pecha.org will able to use the standard way of po file usage.
2. After making these changes, the po file can be integrated seamlessly with tolgee instead of using different script in between to convert po file to json file and vice versa.

## Implementation steps : 
Unique id as key and strings as value are already imported in tolgee, so just need to replace Uid with english strings in template files. (total number of keys in tolgee : 451)

- [x] Apply uid in template files (first 225 strings)
- [x] Apply uid in template files (Next 226 strings)
- [x] Regenerate po file (en, bo, zh) and import in tolgee

**Comment by Lungsangg** [comment]
po file link : https://github.com/OpenPecha/Pecha.org/blob/chore/po_file_usage_correction/locale/en/LC_MESSAGES/django.po

**Comment by drupchen** [comment]
there are still lots of messages that don't use unique ids. 
Some examples:

![Image](https://github.com/user-attachments/assets/d421de45-8ccb-48fb-8192-85c1815eec8d)

![Image](https://github.com/user-attachments/assets/126cdf83-ecb3-44df-a8cd-365d70c523ec)

![Image](https://github.com/user-attachments/assets/06ed01be-ebe5-4cdc-b62f-e376abd12db6)

![Image](https://github.com/user-attachments/assets/3431e379-7c21-4a88-b723-437034593e84)

**Comment by Lungsangg** [comment]
@drupchen la, can you please check again, i have pushed the changes

**Comment by Lungsangg** [comment]
Also i have deleted sheet page strings for translation as sheets.html is no longer in use
