### ISSUE TITLE
Solve the primary language of django to Tibetan instead of Chinese

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#210]
## Current issue : 
1. Last time we have used es (spanish) instead of zh (Chinese) for chinese localization in django because django doesn't accept zh at the time.
2. The primary language was set to chinese, and its need to update to Tibetan
3. two locales are required in Pecha: `zh_hans` and `zh_hant` 

## Implementation steps : 
- [x] Find solution to accept any zh language code in django
- [x] Generate zh po file with its translation (msgstr)
- [x] Sync the zh po file with tolgee
- [x] support both zh_hans and zh_hant
- [x] Set the primary language as Tibetan in django

**Comment by Lungsangg** [comment]
## Note : 

Make sure that django allows to have two chinese locales (one for traditional and one for simplified)

**Comment by drupchen** [comment]
@Lungsangg, I have updated the card to add support of both zh_hans and zh_hant

**Comment by Lungsangg** [comment]
@drupchen la, po file of english, Tibetan, zh-hans, and zh-hant are in tolgee with namespace `django_po_files`
