### ISSUE TITLE
Check for any leftover strings between Figma, Pecha website and Tolgee  (Django side)

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#211]
## Description : 
Translations in Figma are of importance because Tibetan translators got together and translated the strings by referencing to pecha website UI. And its necessary that all the translated strings are there on pecha website. 

On the other hand, Tolgee is the current tool for pecha translation and all the figma translated strings should be there in Tolgee. 

Most importantly all those translated strings should be on pecha website.

## Implementation Steps

Note: open at the same time: Figma on the left, pecha website in the middle, Tolgee at the right

- [x]  Check that what is on the website is the same as in Figma
    - check that all the strings in figma are there in website
    - check that there are no old strings on the website
    - check that all the split strings in Sefaria are now correctly joined with patterns/variables

- [x]  Check that Tolgee has the same strings as Figma and the website

**Comment by lobsam** [comment]
- [x] remaining Chinese  (PO file localization)
![Image](https://github.com/user-attachments/assets/96d00d52-6725-45a3-bd2f-892e0a6399f7)

- [x] not applied  (PO file localization)
![Image](https://github.com/user-attachments/assets/d4be8c85-09ce-418c-b57e-bbad04624670)
![Image](https://github.com/user-attachments/assets/f15029fa-4443-452f-bcb1-4974c9d9f710)

- [x] not applied  (PO file localization)
![Image](https://github.com/user-attachments/assets/4a2cd17b-7fcc-4b9b-b5eb-df4f69867259)
![Image](https://github.com/user-attachments/assets/d37e0add-9394-459e-87c6-1f12e536b196)

- [ ] revision history full of Chinese and Hebrew (PO file localization) Note: there is no translation in figma on revision history page
![Image](https://github.com/user-attachments/assets/6bee47ca-dea3-446f-84c0-421f9e6d88c4)

- [x] not applied  (PO file localization)
![Image](https://github.com/user-attachments/assets/8e32d00d-ccbd-4433-b031-bfa7e2e976ef)
![Image](https://github.com/user-attachments/assets/cb87dd2d-1216-4531-8754-d40523570acf)

- [x] string not hidden  (PO file localization)
![Image](https://github.com/user-attachments/assets/313b3fa9-e3e4-4e8b-b99f-810dd74df325)
![Image](https://github.com/user-attachments/assets/a3410fdf-0a3b-4186-865e-6cd88f47f19e)

- [x] not applied  (PO file localization)
![Image](https://github.com/user-attachments/assets/f1e10a54-2723-4865-8a1c-02f4fc50bdc7)
![Image](https://github.com/user-attachments/assets/bfdb3ac2-fdad-46eb-9ce0-a28c58ced6ea)

- [x] time stamp not applied https://dev.pecha.org/community (PO file localization)
![Image](https://github.com/user-attachments/assets/b4c8d87a-d320-4854-b397-5c0f2bbc8634)

- [x] tab text (PO file localization)
![Image](https://github.com/user-attachments/assets/be484358-07ae-466f-b8ca-2f0ff1cb19db)
![Image](https://github.com/user-attachments/assets/862b495d-d146-48b2-9c1c-42515778c289)

- [x] Sign-up form (PO file localization)
![Image](https://github.com/user-attachments/assets/303b7a5c-c8c9-438b-9559-4fc0e331d315)

should be: གནས་སྟངས་ཞིག་འདེམས།

- [x]  can't test since string is in Chinese (PO file localization)
![Image](https://github.com/user-attachments/assets/6a9edf5c-1d08-4cbe-a355-2c239cfdd7d2)

note: for each entry: 1st image is current state, 2nd image is what is expected

- [x] ![Image](https://github.com/user-attachments/assets/819a250c-ddd4-421b-97c0-2f9bfa98341a)

**Comment by Lungsangg** [comment]
@drupchen la, strings that don't have translation in figma are those key in tolgee with missing Tibetan translation in `django_po_files` namespace

**Comment by Lungsangg** [comment]
Has same translation for both `Enter new password' and 'new password' in figma
