### ISSUE TITLE
Tolgee: put all the strings from the UI in a subset of strings

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#212]
## Description:

In tolgee, every string is not necessarily is in use right now, so those strings that are currently used in pecha.org UI need to be tagged with "main_string_po" so that translators can focus on only required strings.

## Steps:

- open side by side Tolgee and pecha.org
- open every page of pecha and check that each string is tagged with `main_strings` in Tolgee

## Implementation steps: 

- [x] Registration/Login page strings
- [x] profile page strings
- [x] 404/500 page strings
- [x] setting/account page strings
- [x] collection date strings
- [x] forms.py strings
- [x] about page strings
