### ISSUE TITLE
CR004: remove warning message in reCAPTCHA

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#56]
![image](https://github.com/user-attachments/assets/181fe9ed-733a-4fb1-b238-613b116e39c5)

**Description:**

Right now pecha.org is using only test mode reCAPTCHA and need to integrate production google reCAPTCHA.

**Implementation steps :** 

- [x] Setup reCAPTCHA project in google console ( using hello@pecha.org credential)
- [x] Generate public and private key  
- [x] reintegrate production reCAPTCHA in django
- [x] setup environment variable in render for dev, staging and production
