### ISSUE TITLE
CR016: export sheet to Google Drive throws error page

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#64]
## Location

- Open a sheet in editing mode
- click on "File"
- click on "Export to Google Drive"

## Issue
![image](https://github.com/user-attachments/assets/8b270c7b-0b3b-4c01-af99-2c371cbbfac8)
 
**Implementation steps :** 

- [x] Setup pecha project in google console
- [x] configure OAuth 2.0  and download secret key
- [x] integrate in django and test export to google drive 
- [x] Solve "You're accessing the development server over HTTPS, but it only supports HTTP" error
- [x] Setup environment variable in render

**Expected result :** 
Exported sheet will be in user's "My Drive" content.

**Comment by Lungsangg** [comment]
@drupchen la, can you use drupchen@pecha.org for google drive credential when testing this feature because right now google oauth is on test mode and i have applied for publish mode (which will take some time for google to verify). Once it get published, any user can use the sheet export to google drive feature.

**Comment by Lungsangg** [comment]
Sheet in google drive : 
![Image](https://github.com/user-attachments/assets/4dca6944-0c58-480c-8f18-4c3158cc3427)

Changed "Sefaria" to "Pecha" and localized. (ie; need to regenerate tibetan po file)
