### ISSUE TITLE
RFC002: Chinese localization implementation in code

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/pecha.org-feedbucket#90]
**This RFC002 solves** [RFW01](https://github.com/OpenPecha/pecha.org-roadmap/issues/50)
### Description :

Pecha.org (which is an instance of sefaria.org) has two language ie, English and Tibetan. And need to add Chinese language feature (with more languages in future). With current localization setup, for backend, django po file is used and in frontend a js file (which have strings in english Tibetan key value pair).

A chinese language feature need to implement in code for this task.

### Dependencies :

- modified string.js file that contains English, Tibetan and Chinese strings used in frontend.
- A django po file for chinese translations.

### Justification :

There are two method to implement multiple language support for pecha.org. First one is to customize currenly implemented method by sefaria and second one is to discard all the sefaria method and implement reacti8n library on frontend. 
We chose the first method as it is implementable in the current given time and implementing reacti8n library would needs lots of changes in code that sefaria have put in place.

#### React 
    

- [x] OpenPecha/Pecha.org#272
- [x] OpenPecha/Pecha.org#273
- [x] OpenPecha/Pecha.org#275
    
#### Django

- [x] OpenPecha/Pecha.org#269
- [x] OpenPecha/Pecha.org#270
- [x] OpenPecha/Pecha.org#271
- [x] OpenPecha/Pecha.org#277

**Comment by Lungsangg** [comment]
@kaldan007 @drupchen, Sandup and me are going though code today and will meet tomorrow morning to write rfc.
